import jsPDF from "jspdf";
import autoTable from 'jspdf-autotable';

const PDFExport = {
  downloadReportAsPDF: (report) => {
    const doc = new jsPDF();
    
    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("SafeStreet.com.au Incident Report", 105, 20, null, null, "center");
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Report ID: ${report._id}`, 15, 35);
    doc.text(`Date: ${new Date(report.date).toLocaleDateString()}`, 15, 45);

    // Incident Details
    autoTable(doc, {
      startY: 55,
      head: [["Field", "Details"]],
      body: [
        ["Vehicle Registration", report.vehicleRegistration || "N/A"],
        ["Location", report.location || "N/A"],
        ["Incident Type", report.incidentType || "N/A"],
        ["Status", report.status.toUpperCase()],
        ["Date Reported", new Date(report.date).toLocaleDateString()],
        ["Time Reported", new Date(report.date).toLocaleTimeString()]
      ],
      theme: "grid",
      styles: { fontSize: 10 },
      headStyles: { fillColor: [79, 70, 229] }
    });

    // Media Availability
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Media Status", 15, doc.lastAutoTable.finalY + 15);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(
      report.mediaFlag ? "Media Available" : "No Media Uploaded",
      15,
      doc.lastAutoTable.finalY + 25
    );

    // Risk Assessment
    let riskScore = 0;
    const incidentWeights = {
      "Speeding": 8,
      "Running Red Light": 9,
      "Reckless Driving": 10,
      "Tailgating": 7,
      "Other": 5
    };
    
    const baseScore = incidentWeights[report.incidentType] || 5;
    const mediaBonus = report.mediaFlag ? 2 : 0;
    riskScore = Math.min(10, baseScore + mediaBonus);

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Risk Assessment", 15, doc.lastAutoTable.finalY + 40);
    
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 50,
      body: [
        ["Risk Score", `${riskScore.toFixed(1)} / 10`],
        ["Risk Level", riskScore >= 8 ? "High" : riskScore >= 6 ? "Medium" : "Low"],
        ["Insurance Impact", riskScore >= 8 ? "Significant" : riskScore >= 6 ? "Moderate" : "Minimal"]
      ],
      theme: "plain",
      styles: { fontSize: 10 }
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text(
        `Generated by SafeStreet.com.au - Page ${i} of ${pageCount}`,
        105,
        doc.internal.pageSize.height - 10,
        null,
        null,
        "center"
      );
      doc.text(
        `Confidential - For authorized use only`,
        105,
        doc.internal.pageSize.height - 5,
        null,
        null,
        "center"
      );
    }

    // Save the PDF with a proper filename
    doc.save(`SafeStreet_Report_${report.vehicleRegistration || "Unknown"}.pdf`);
  },
  
  exportAnalytics: (reports, format = "pdf") => {
    if (format !== "pdf") {
      console.error("Only PDF export is implemented in this demo");
      return;
    }
    
    const doc = new jsPDF();
    
    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("SafeStreet Analytics Report", 105, 20, null, null, "center");
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 105, 30, null, null, "center");

    // Incident Summary
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Incident Summary", 15, 45);
    
    // Group by incident type
    const incidentCounts = reports.reduce((acc, report) => {
      acc[report.incidentType] = (acc[report.incidentType] || 0) + 1;
      return acc;
    }, {});
    
    // Format for table
    const incidentData = Object.keys(incidentCounts).map(type => [
      type,
      incidentCounts[type],
      ((incidentCounts[type] / reports.length) * 100).toFixed(1) + "%"
    ]);
    
    // Add total row
    incidentData.push([
      "Total",
      reports.length,
      "100%"
    ]);
    
    autoTable(doc, {
      startY: 55,
      head: [["Incident Type", "Count", "Percentage"]],
      body: incidentData,
      theme: "grid",
      styles: { fontSize: 10 },
      headStyles: { fillColor: [79, 70, 229] }
    });
    
    // High Risk Drivers
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("High Risk Drivers", 15, doc.lastAutoTable.finalY + 20);
    
    // Group by vehicle registration
    const driverReports = {};
    reports.forEach(report => {
      if (!driverReports[report.vehicleRegistration]) {
        driverReports[report.vehicleRegistration] = [];
      }
      driverReports[report.vehicleRegistration].push(report);
    });
    
    // Calculate risk scores
    const drivers = Object.keys(driverReports).map(registration => {
      const driverData = driverReports[registration];
      const incidents = driverData.length;
      
      // Simple risk algorithm
      const incidentTypeScores = driverData.reduce((acc, report) => {
        const typeScores = {
          "Speeding": 2,
          "Running Red Light": 3,
          "Reckless Driving": 4,
          "Tailgating": 1.5,
          "Other": 1
        };
        return acc + (typeScores[report.incidentType] || 1);
      }, 0);
      
      const score = Math.min(10, (incidentTypeScores / incidents) * 2.5);
      
      return {
        registration,
        incidents,
        score,
        primaryType: getMostCommonType(driverData)
      };
    });
    
    // Sort by risk score (descending) and take top 10
    const topRiskDrivers = drivers
      .sort((a, b) => b.score - a.score)
      .slice(0, 10)
      .map(driver => [
        driver.registration,
        driver.incidents,
        driver.primaryType,
        driver.score.toFixed(1) + " / 10",
        driver.score >= 8 ? "High" : driver.score >= 6 ? "Medium" : "Low"
      ]);
    
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 30,
      head: [["Registration", "Incidents", "Primary Type", "Risk Score", "Risk Level"]],
      body: topRiskDrivers,
      theme: "grid",
      styles: { fontSize: 10 },
      headStyles: { fillColor: [79, 70, 229] }
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text(
        `Generated by SafeStreet.com.au - Page ${i} of ${pageCount}`,
        105,
        doc.internal.pageSize.height - 10,
        null,
        null,
        "center"
      );
      doc.text(
        `Confidential - For authorized use only`,
        105,
        doc.internal.pageSize.height - 5,
        null,
        null,
        "center"
      );
    }

    // Save the PDF
    doc.save(`SafeStreet_Analytics_${new Date().toISOString().split('T')[0]}.pdf`);
  }
};

// Helper function to get most common incident type for a driver
function getMostCommonType(reports) {
  const typeCounts = reports.reduce((acc, report) => {
    acc[report.incidentType] = (acc[report.incidentType] || 0) + 1;
    return acc;
  }, {});
  
  return Object.keys(typeCounts).reduce((a, b) => typeCounts[a] > typeCounts[b] ? a : b);
}

export default PDFExport;